[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main
mypy_path = apps
explicit_package_bases = True
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
ignore_missing_imports = False

[mypy.plugins.django-stubs]
django_settings_module = "interactome.settings.dev"

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-lxml.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-django_celery_beat.*]
ignore_missing_imports = True

[mypy-django_celery_results.*]
ignore_missing_imports = True

[mypy-structlog.*]
ignore_missing_imports = True

[mypy-nltk]
ignore_missing_imports = True
follow_imports = silent

[mypy-nltk.*]
ignore_missing_imports = True
follow_imports = silent

[mypy-tiktoken]
ignore_missing_imports = True
follow_imports = silent

[mypy-tiktoken.*]
ignore_missing_imports = True
follow_imports = silent

[mypy-gilda]
ignore_missing_imports = True
follow_imports = silent

[mypy-gilda.*]
ignore_missing_imports = True
follow_imports = silent

[mypy-*.tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-corpus.tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-core.tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-graph.tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-libsbml]
ignore_missing_imports = True

[mypy-libsbml.*]
ignore_missing_imports = True

[mypy-sbml.tests.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-*.migrations.*]
ignore_errors = True
