# Generated by Django 5.2.14 on 2026-05-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("networks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pubmed", "pubmed"),
                            ("pubmed_full", "pubmed_full"),
                            ("elink", "elink"),
                            ("europe_pmc", "europe_pmc"),
                        ],
                        max_length=24,
                    ),
                ),
                ("query", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("n_pmids_seen", models.PositiveIntegerField(default=0)),
                ("n_papers_created", models.PositiveIntegerField(default=0)),
                ("n_papers_updated", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "corpus_ingestrun",
                "indexes": [
                    models.Index(
                        fields=["source", "started_at"], name="corpus_inge_source_ff5d7a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("pmid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("doi", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("pmcid", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("title", models.TextField()),
                ("abstract", models.TextField(blank=True, default="")),
                ("authors", models.JSONField(blank=True, default=list)),
                ("journal", models.CharField(blank=True, default="", max_length=256)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("entrez_date", models.DateField(blank=True, db_index=True, null=True)),
                ("publication_types", models.JSONField(blank=True, default=list)),
                ("mesh_terms", models.JSONField(blank=True, default=list)),
                ("pubtator_entities", models.JSONField(blank=True, default=list)),
                ("is_original", models.BooleanField(blank=True, null=True)),
                ("classification_confidence", models.FloatField(blank=True, null=True)),
                ("classification_reason", models.TextField(blank=True, default="")),
                (
                    "full_text_status",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("abstract_only", "abstract_only"),
                            ("pmc_jats", "pmc_jats"),
                            ("grobid_tei", "grobid_tei"),
                            ("fetch_failed", "fetch_failed"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("fulltext_s3_key", models.CharField(blank=True, default="", max_length=256)),
                ("fulltext_fetch_error", models.TextField(blank=True, default="")),
                (
                    "ingest_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("ingested", "ingested"),
                            ("classified", "classified"),
                            ("fetched", "fetched"),
                            ("chunked", "chunked"),
                            ("done", "done"),
                            ("failed", "failed"),
                            ("ingest_failed", "ingest_failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("ingest_attempts", models.PositiveIntegerField(default=0)),
                ("ingest_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("ingest_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "corpus_paper",
                "indexes": [
                    models.Index(
                        fields=["ingest_status", "entrez_date"],
                        name="corpus_pape_ingest__8cf367_idx",
                    ),
                    models.Index(fields=["is_original"], name="corpus_pape_is_orig_58819a_idx"),
                    models.Index(
                        fields=["full_text_status"], name="corpus_pape_full_te_cffde1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperRelevance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("score", models.FloatField()),
                (
                    "classified_by",
                    models.CharField(
                        choices=[
                            ("cheap_keyword", "cheap_keyword"),
                            ("cheap_pubtator", "cheap_pubtator"),
                            ("llm:qwen3:8b", "llm:qwen3:8b"),
                        ],
                        default="cheap_keyword",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_relevances",
                        to="networks.network",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relevances",
                        to="corpus.paper",
                    ),
                ),
            ],
            options={
                "db_table": "corpus_paperrelevance",
                "indexes": [
                    models.Index(fields=["network", "score"], name="corpus_pape_network_c6c4f6_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("paper", "network"), name="uniq_paper_network_relevance"
                    )
                ],
            },
        ),
    ]
