# Generated by Django 5.2.14 on 2026-05-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extract", "0002_seed_prompt"),
        ("graph", "0001_initial"),
        ("networks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("activates", "activates"),
                            ("inhibits", "inhibits"),
                            ("binds", "binds"),
                            ("phosphorylates", "phosphorylates"),
                            ("dephosphorylates", "dephosphorylates"),
                            ("ubiquitinates", "ubiquitinates"),
                            ("deubiquitinates", "deubiquitinates"),
                            ("methylates", "methylates"),
                            ("acetylates", "acetylates"),
                            ("deacetylates", "deacetylates"),
                            ("transcribes", "transcribes"),
                            ("represses", "represses"),
                            ("cleaves", "cleaves"),
                            ("regulates", "regulates"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("belief_score", models.FloatField(db_index=True, default=0.0)),
                ("n_supporting_papers", models.PositiveIntegerField(default=0)),
                ("n_models_agreeing", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "candidate"),
                            ("accepted", "accepted"),
                            ("conflicted", "conflicted"),
                            ("rejected", "rejected"),
                        ],
                        db_index=True,
                        default="candidate",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_edges",
                        to="graph.entity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_edges",
                        to="graph.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EdgeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="graph.edge",
                    ),
                ),
                (
                    "raw_ppi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edge_evidence",
                        to="extract.rawppi",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="edge",
            name="raw_ppis",
            field=models.ManyToManyField(
                related_name="edges", through="graph.EdgeEvidence", to="extract.rawppi"
            ),
        ),
        migrations.CreateModel(
            name="NetworkEdgeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("relevance", models.FloatField(db_index=True, default=1.0)),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_memberships",
                        to="graph.edge",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edge_memberships",
                        to="networks.network",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("intra_paper", "intra-paper"),
                            ("inter_paper", "inter-paper"),
                            ("inter_model", "inter-model"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("auto_resolved", "auto-resolved"),
                            ("human_resolved", "human-resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                ("reasoning", models.TextField(blank=True, default="")),
                (
                    "edge_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_a",
                        to="graph.edge",
                    ),
                ),
                (
                    "edge_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_b",
                        to="graph.edge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edge_a", "edge_b", "conflict_type"),
                        name="conflict_unique_pair_type",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="edgeevidence",
            constraint=models.UniqueConstraint(
                fields=("edge", "raw_ppi"), name="edgeevidence_unique_edge_raw_ppi"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(fields=["source", "target"], name="graph_edge_source__983d96_idx"),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["status", "belief_score"], name="graph_edge_status_9230bc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "relation"), name="edge_unique_source_target_relation"
            ),
        ),
        migrations.AddIndex(
            model_name="networkedgemembership",
            index=models.Index(
                fields=["network", "relevance"], name="graph_netwo_network_661e79_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="networkedgemembership",
            constraint=models.UniqueConstraint(
                fields=("network", "edge"), name="networkedgemembership_unique_network_edge"
            ),
        ),
    ]
