# Generated by Django 5.2.14 on 2026-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_remove_networkedgemembership_networkedgemembership_unique_network_edge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='auto_resolve_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='resolved_relation',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
