# Generated by Django 5.2.x — Phase 6 fix: durable idempotency for detect_affected_networks.
#
# Adds a conditional UniqueConstraint on (network, pending_paper_id) WHERE edge IS NULL
# so that concurrent / duplicate calls to detect_affected_networks cannot insert duplicate
# pending-extraction placeholder rows at the DB level.
#
# This constraint does NOT affect:
#   - Phase 3 reassign_network_membership (always writes non-null edge — covered by the
#     separate networkedgemembership_unique_network_edge constraint).
#   - Phase 8 projection (read-only; never inserts NetworkEdgeMembership rows).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0004_conflict_auto_resolve_attempted_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="networkedgemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(edge__isnull=True),
                fields=("network", "pending_paper_id"),
                name="networkedgemembership_unique_network_pending_paper",
            ),
        ),
    ]
