"""ZIP bundle assembly + auto-generated README per spec §7.

Final on-disk layout when extracted::

    <network_code>_v<semver>/
        model.sbml
        edges.csv
        evidence.csv
        README.md

Real field names:
- network.title (NOT network.name — Network model has title not name)
"""

from __future__ import annotations

import io
import textwrap
import zipfile
from datetime import UTC, datetime
from typing import Any


def zip_filename(network_code: str, semver: str) -> str:
    """Return the canonical ZIP filename: ``<code>_v<semver>.zip``."""
    return f"{network_code}_v{semver}.zip"


def bundle_artifact(
    *,
    network_code: str,
    semver: str,
    sbml_bytes: bytes,
    edges_csv: bytes,
    evidence_csv: bytes,
    readme_md: str,
) -> bytes:
    """Build the per-version ZIP and return it as bytes."""
    folder = f"{network_code}_v{semver}"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{folder}/model.sbml", sbml_bytes)
        zf.writestr(f"{folder}/edges.csv", edges_csv)
        zf.writestr(f"{folder}/evidence.csv", evidence_csv)
        zf.writestr(
            f"{folder}/README.md",
            readme_md.encode("utf-8") if isinstance(readme_md, str) else readme_md,
        )
    return buf.getvalue()


def generate_readme(
    *,
    network: Any,
    semver: str,
    n_species: int,
    n_reactions: int,
    n_edges: int,
    n_papers: int,
    edges: Any,  # noqa: ARG001 — future use (per-edge stats)
) -> str:
    """Build a human-readable README.md for the bundle.

    Uses ``network.title`` (the human-readable name per Networks model).
    """
    now = datetime.now(UTC).isoformat()
    return textwrap.dedent(
        f"""\
        # {network.title}

        **Version:** v{semver}
        **Generated:** {now}
        **Network code:** `{network.code}`
        **Category:** {network.category}

        Auto-generated by the IVD Regulatory Network Atlas
        (https://interactome.simbiosys.sb.upf.edu).

        ---

        ## Contents

        | File | Description |
        |---|---|
        | `model.sbml` | SBML-qual document; {n_species} qualitative species, {n_reactions} transitions |
        | `edges.csv` | Tabular edge list with belief scores and reviewer status |
        | `evidence.csv` | Per-paper provenance for every edge |
        | `README.md` | This file |

        ## Statistics

        - Species (entities): {n_species}
        - Transitions (edges): {n_reactions}
        - Total accepted edges: {n_edges}
        - Distinct supporting papers: {n_papers}

        ## Loading into downstream tools

        ### GINsim
        ```
        ginsim -import model.sbml
        ```

        ### CellNOpt (R)
        ```r
        library(CellNOptR)
        model <- readSBMLQual("model.sbml")
        ```

        ### Cytoscape
        File -> Import -> Network from File -> select `model.sbml`
        (requires the SBML and BiNoM apps).

        ## edges.csv columns

        | Column | Meaning |
        |---|---|
        | `source_symbol`, `source_id`, `source_type` | Source node (HGNC symbol, identifiers.org URI, entity type) |
        | `relation` | activates / inhibits / binds / phosphorylates / ... |
        | `target_symbol`, `target_id`, `target_type` | Target node |
        | `belief` | Posterior belief 0..1 |
        | `n_supporting_papers` | Distinct PMIDs supporting this edge |
        | `n_models_agreeing` | How many of the 7 Ollama models extracted this |
        | `reviewer_status` | unreviewed / approved / rejected / conflicted |
        | `first_seen`, `last_seen` | Edge lifetime timestamps |

        ## evidence.csv columns

        | Column | Meaning |
        |---|---|
        | `edge_id` | Foreign key into `edges.csv` |
        | `pmid` | Source paper |
        | `chunk_excerpt` | Sentence containing the evidence span |
        | `evidence_span_start`, `evidence_span_end` | Char offsets into the chunk |
        | `extractor_model` | Ollama model that extracted this PPI |
        | `extraction_logprob` | Logprob at the relation-type token |
        | `extracted_at` | Timestamp |

        ## How to cite

        Chemorion F, et al. *IVD Regulatory Network Atlas: an autonomous
        PubMed -> SBML-qual pipeline for intervertebral disc disease.*
        SIMBIOsys / BCN MedTech / UPF DTIC, 2026.
        Contact: francis.chemorion@upf.edu

        ## License

        UPF / SIMBIOsys research artifact. Reuse for non-commercial
        academic research is permitted with attribution. Contact before
        redistributing.
        """
    )
