# Generated by Django 5.2.14 on 2026-05-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OntologyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("gene", "Gene"),
                            ("protein", "Protein"),
                            ("mirna", "microRNA"),
                            ("lncrna", "lncRNA"),
                            ("metabolite", "Metabolite"),
                            ("complex", "Complex"),
                            ("cell_type", "Cell type"),
                            ("phenotype", "Phenotype"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("preferred_label", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("compartment", models.CharField(blank=True, default="cytoplasm", max_length=32)),
                ("canonical_uri", models.URLField(blank=True, default="")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "preferred_label"],
                        name="core_ontolo_entity__20c95c_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("preferred_label", ""), _negated=True),
                        name="ontologyentity_label_nonempty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("HGNC", "HGNC"),
                            ("UNIPROT", "UniProt"),
                            ("ENSEMBL", "Ensembl"),
                            ("NCBI_GENE", "NCBI Gene"),
                            ("CHEBI", "ChEBI"),
                            ("MIRBASE", "miRBase"),
                            ("MESH", "MeSH"),
                            ("GO", "Gene Ontology"),
                            ("CL", "Cell Ontology"),
                            ("DOID", "Disease Ontology"),
                            ("REACTOME", "Reactome"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=128)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="core.ontologyentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["scheme", "value"], name="core_identi_scheme_191198_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "scheme", "value"),
                        name="identifier_unique_per_entity_scheme_value",
                    )
                ],
            },
        ),
    ]
