# Generated by Django 5.2.14 on 2026-05-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("category", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("root_entity_aliases", models.JSONField(blank=True, default=list)),
                ("root_entities", models.JSONField(blank=True, default=list)),
                (
                    "pipeline_status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("refreshing", "refreshing"),
                            ("stale", "stale"),
                            ("version_draft", "version_draft"),
                            ("verified", "verified"),
                        ],
                        default="idle",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "networks_network",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="FamilyFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("family_name", models.CharField(max_length=128)),
                ("uniprot_family_id", models.CharField(blank=True, default="", max_length=32)),
                ("members", models.JSONField(blank=True, default=list)),
                ("is_inclusion", models.BooleanField(default=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_filters",
                        to="networks.network",
                    ),
                ),
            ],
            options={
                "db_table": "networks_familyfilter",
            },
        ),
        migrations.CreateModel(
            name="NetworkQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("discovery", "discovery"),
                            ("triage_cheap", "triage_cheap"),
                            ("expansion", "expansion"),
                        ],
                        max_length=24,
                    ),
                ),
                ("query", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="networks.network",
                    ),
                ),
            ],
            options={
                "db_table": "networks_networkquery",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("network", "purpose"), name="uniq_network_query_purpose"
                    )
                ],
            },
        ),
    ]
