# Generated by Django 5.2.14 on 2026-05-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("model_name", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("heartbeat", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("response_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_runs",
                        to="papers.chunk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("version", models.CharField(max_length=32, unique=True)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="extract_prompt_only_one_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawPPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("subject", models.CharField(max_length=128)),
                ("object", models.CharField(max_length=128)),
                ("relation", models.CharField(max_length=32)),
                ("evidence_span", models.TextField()),
                ("evidence_offset_start", models.PositiveIntegerField()),
                ("evidence_offset_end", models.PositiveIntegerField()),
                ("cell_type", models.CharField(blank=True, max_length=128, null=True)),
                ("stimulus", models.CharField(blank=True, max_length=256, null=True)),
                ("confidence", models.FloatField()),
                ("relation_logprob", models.FloatField(blank=True, null=True)),
                ("ungrounded", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_ppis",
                        to="extract.extractionrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="extractionrun",
            index=models.Index(
                fields=["status", "heartbeat"], name="extract_ext_status_3d2fa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionrun",
            index=models.Index(
                fields=["model_name", "status"], name="extract_ext_model_n_21722e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrun",
            constraint=models.UniqueConstraint(
                fields=("chunk", "model_name", "prompt_version"), name="extract_run_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="rawppi",
            index=models.Index(fields=["run"], name="extract_raw_run_id_c29df0_idx"),
        ),
        migrations.AddIndex(
            model_name="rawppi",
            index=models.Index(fields=["ungrounded"], name="extract_raw_ungroun_5b66f8_idx"),
        ),
    ]
