# Generated by Django 5.2.14 on 2026-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("provider", models.CharField(max_length=64, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("refill_per_sec", models.FloatField()),
                ("current_tokens", models.FloatField()),
            ],
            options={
                "db_table": "schedule_ratelimitbucket",
            },
        ),
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("cadence_seconds", models.PositiveIntegerField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("never_run", "never_run"),
                            ("running", "running"),
                            ("done", "done"),
                            ("failed", "failed"),
                        ],
                        default="never_run",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "schedule_scheduledjob",
            },
        ),
        migrations.CreateModel(
            name="Watermark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("source", models.CharField(max_length=64, unique=True)),
                ("last_entrez_date", models.DateField(blank=True, null=True)),
                ("last_pmid_seen", models.BigIntegerField(blank=True, null=True)),
                ("resumption_token", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "schedule_watermark",
            },
        ),
    ]
