# Generated by Django 5.2.14 on 2026-05-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("corpus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_original", models.BooleanField()),
                ("confidence", models.FloatField()),
                (
                    "classifier",
                    models.CharField(
                        choices=[
                            ("rule:pubtype", "rule:pubtype"),
                            ("llm:qwen3:8b", "llm:qwen3:8b"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification",
                        to="corpus.paper",
                    ),
                ),
            ],
            options={
                "db_table": "papers_paperclassification",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("order_index", models.PositiveSmallIntegerField()),
                ("doco_type", models.CharField(db_index=True, max_length=32)),
                ("doco_iri", models.URLField(blank=True, default="")),
                ("heading", models.CharField(blank=True, default="", max_length=512)),
                ("body_text", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="corpus.paper",
                    ),
                ),
            ],
            options={
                "db_table": "papers_section",
                "ordering": ["paper", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("chunk_index", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField()),
                ("char_offset_start", models.PositiveIntegerField()),
                ("char_offset_end", models.PositiveIntegerField()),
                ("processed_by_models", models.JSONField(blank=True, default=list)),
                (
                    "paper",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="corpus.paper",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="papers.section",
                    ),
                ),
            ],
            options={
                "db_table": "papers_chunk",
            },
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["paper", "doco_type"], name="papers_sect_paper_i_d02f91_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("paper", "order_index"), name="uniq_paper_section_index"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["paper", "section"], name="papers_chun_paper_i_ebc770_idx"),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("section", "chunk_index"), name="uniq_section_chunk_index"
            ),
        ),
    ]
