# Generated by Django 5.2.14 on 2026-05-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sbml.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("graph", "0002_edge_evidence_conflict_membership"),
        ("networks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "semver",
                    models.CharField(max_length=32, validators=[sbml.models.validate_semver]),
                ),
                ("frozen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("n_species", models.PositiveIntegerField()),
                ("n_reactions", models.PositiveIntegerField()),
                ("n_edges", models.PositiveIntegerField()),
                ("sbml_s3_key", models.CharField(blank=True, max_length=512)),
                ("csv_s3_key", models.CharField(blank=True, max_length=512)),
                ("evidence_csv_s3_key", models.CharField(blank=True, max_length=512)),
                ("zip_s3_key", models.CharField(blank=True, max_length=512)),
                ("generation_error", models.TextField(blank=True)),
                (
                    "generated_from_edges",
                    models.ManyToManyField(
                        blank=True, related_name="model_versions", to="graph.edge"
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="networks.network",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("sbml", "SBML-qual document"),
                            ("edges_csv", "edges.csv"),
                            ("evidence_csv", "evidence.csv"),
                            ("zip", "Per-version ZIP bundle"),
                        ],
                        max_length=16,
                    ),
                ),
                ("s3_key", models.CharField(max_length=512)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "downloaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sbml_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downloads",
                        to="sbml.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["network", "-created_at"], name="sbml_modelv_network_c77640_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                fields=("network", "semver"), name="uniq_modelversion_network_semver"
            ),
        ),
        migrations.AddIndex(
            model_name="exportartifact",
            index=models.Index(
                fields=["model_version", "-downloaded_at"], name="sbml_export_model_v_8cacc1_idx"
            ),
        ),
    ]
