# Generated by Django 5.2.14 on 2026-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sbml", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="frozen_edges",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
